[profile.default]
via_ir = true
src = "src"
out = "out"
libs = ["lib"]


# Configure remappings
remappings = [
  "@std=lib/forge-std/src/",
  "@openzeppelin=lib/openzeppelin-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
